name: phylogenetic-datascience
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7  # the current default on mybinder
  - jupyter
  - numpy
  - pandas
  - scipy
  - numba
  - loguru
  - requests
  - msprime>=1.0
  # - raxml
  # - toytree>=3.0
  - pip
  - pip:
    - git+https://github.com/eaton-lab/toytree.git@toy3#egg=toytree
